export { default as Home } from './Home'
export { default as ErrorPage } from './ErrorPage'
export { default as Detail } from './Detail'
export { default as Whistlist } from './Whistlist'
export { default as Upload } from './Upload'
export { default as Main } from './Main'
export { default as Login } from './Login'
export { default as Register } from './Register'
